# Generated by Django 5.1.5 on 2025-02-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('high_school_grad', models.IntegerField()),
                ('first_term', models.IntegerField()),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('concentration', models.CharField(blank=True, max_length=100, null=True)),
                ('minors', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('subject', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=10)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('credits', models.IntegerField()),
                ('course_attribute', models.CharField(blank=True, max_length=10, null=True)),
                ('institution', models.CharField(max_length=50)),
                ('student_attribute', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
