from collections import namedtuple

CourseData = namedtuple("CourseData", ["subject", "number", "name", "credits"])

halp = [{'name': 'Program Summary', 'type': 'credits', 'required_credits': None, 'courses': [], 'children': []},
        {'name': 'Program Information', 'type': 'credits', 'required_credits': None, 'courses': [], 'children': []},
        {'name': 'General Education Requirement (30-35 Credits)', 'type': 'credits', 'required_credits': 30,
         'courses': [],
         'children': []},
        {'name': 'Bachelor of Science (B.S.) Degree Requirement (12 Credits*)', 'type': 'credits',
         'required_credits': 12,
         'courses': [], 'children': []},
        {'name': 'Exercise Science Curriculum (47-56 Credits)', 'type': 'credits', 'required_credits': 47,
         'courses': [],
         'children': [{'name': 'Core Requirements (34-35 Credits)', 'type': 'credits', 'required_credits': 34,
                       'courses': [CourseData(subject='PE', number='1098', name='Wellness Dynamics', credits=3),
                                   CourseData(subject='KIN', number='2000', name='Introduction to Exercise Science',
                                              credits=1),
                                   CourseData(subject='KIN', number='2020', name='Functional Kinesiology', credits=2),
                                   CourseData(subject='KIN', number='3050', name='Motor Learning', credits=3),
                                   CourseData(subject='KIN', number='3060', name='Sport and Exercise Biomechanics',
                                              credits=3),
                                   CourseData(subject='KIN', number='3065', name='Sport and Exercise Biomechanics Lab',
                                              credits=1),
                                   CourseData(subject='KIN', number='3070', name='Exercise Physiology', credits=3),
                                   CourseData(subject='KIN', number='3075', name='Exercise Physiology Lab', credits=1),
                                   CourseData(subject='KIN', number='3080',
                                              name='Athletic Training and Sports Medicine',
                                              credits=3),
                                   CourseData(subject='KIN', number='3085',
                                              name='Athletic Training and Sports Medicine Lab',
                                              credits=1),
                                   CourseData(subject='KIN', number='4010', name='Methods of Sports Conditioning',
                                              credits=3),
                                   CourseData(subject='KIN', number='4020',
                                              name='Research Methods and Statistics in Exercise Science', credits=3),
                                   CourseData(subject='KIN', number='4030',
                                              name='Clinical Applications of Exercise Science',
                                              credits=3),
                                   CourseData(subject='KIN', number='4035',
                                              name='Clinical Applications of Exercise Science Lab',
                                              credits=1),
                                   CourseData(subject='KIN', number='4040', name='Exercise Testing and Prescription',
                                              credits=3),
                                   CourseData(subject='PE', number='1543',
                                              name='Advanced First Aid-Emergency Care-CPR (must either take class',
                                              credits=1)], 'children': []},
                      {'name': 'Biology Requirements (4 or 12 Credits)', 'type': 'credits',
                       'required_credits': '4 or 12',
                       'courses': [CourseData(subject='BIOL', number='1020', name='Human Biology', credits=3),
                                   CourseData(subject='BIOL', number='1025', name='Human Biology Lab', credits=1),
                                   CourseData(subject='BIOL', number='1610', name='General Biology I', credits=3),
                                   CourseData(subject='BIOL', number='1615', name='General Biology Lab I', credits=1),
                                   CourseData(subject='BIOL', number='2320', name='Human Anatomy', credits=3),
                                   CourseData(subject='BIOL', number='2325', name='Human Anatomy Lab', credits=1),
                                   CourseData(subject='BIOL', number='2323', name='Human Anatomy Lab (Online)',
                                              credits=1),
                                   CourseData(subject='BIOL', number='2420', name='Human Physiology', credits=3),
                                   CourseData(subject='BIOL', number='2425', name='Human Physiology Lab', credits=1),
                                   CourseData(subject='BIOL', number='2423', name='Human Physiology Lab (Online)',
                                              credits=1)],
                       'children': []},
                      {'name': 'Exercise Science Electives (9 Credits)', 'type': 'credits', 'required_credits': 9,
                       'courses': [
                           CourseData(subject='KIN', number='4070', name='Advanced Exercise Physiology', credits=3),
                           CourseData(subject='KIN', number='4080', name='Obesity and Weight Management', credits=3),
                           CourseData(subject='KIN', number='4100', name='ECG Interpretation', credits=3),
                           CourseData(subject='KIN', number='4400', name='Evaluation of Musculoskeletal Injuries',
                                      credits=3),
                           CourseData(subject='KIN', number='4410', name='Therapeutic Exercise and Rehabilitation',
                                      credits=3),
                           CourseData(subject='KIN', number='4450', name='Therapeutic Modalities', credits=3),
                           CourseData(subject='KIN', number='4800', name='Studies in Exercise Sciences', credits=3),
                           CourseData(subject='KIN', number='4890',
                                      name='Internship 1-8 Credit(s) (student must obtain 3 credits from this course to meet course requirements)',
                                      credits=1),
                           CourseData(subject='NFS', number='3020', name='Nutrition as Related to Fitness and Sports',
                                      credits=3),
                           CourseData(subject='PE', number='4740', name='Coaching Leadership and Administration',
                                      credits=3),
                           CourseData(subject='PE', number='4750', name='Psycho-Social Aspects of Athletics',
                                      credits=3)], 'children': []}]},
        {'name': 'Free Electives (29-49 Credits)', 'type': 'credits', 'required_credits': 29, 'courses': [],
         'children': []},
        {'name': 'Total Credits, B.S. Degree: 120', 'type': 'credits', 'required_credits': None, 'courses': [],
         'children': []},
        {'name': 'Program Learning Outcomes', 'type': 'credits', 'required_credits': None, 'courses': [],
         'children': []}]
