# Generated by Django 5.1.5 on 2025-03-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=8)),
                ('course_number', models.CharField(max_length=8)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorMapping',
            fields=[
                ('major_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('major_name_web', models.CharField(max_length=255, unique=True)),
                ('major_name_registrar', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('high_school_grad', models.IntegerField()),
                ('first_term', models.IntegerField()),
                ('term', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('credits', models.IntegerField()),
                ('course_attributes', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(max_length=255)),
                ('student_attributes', models.BigIntegerField(blank=True, null=True)),
                ('counts_toward_major', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.course')),
            ],
        ),
        migrations.CreateModel(
            name='MajorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('Core', 'Core Requirement'), ('Elective', 'Elective'), ('Not Applicable', 'Not Applicable')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.majormapping')),
            ],
            options={
                'unique_together': {('major', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_year', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.majormapping')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentrecord')),
            ],
            options={
                'unique_together': {('student', 'major')},
            },
        ),
        migrations.CreateModel(
            name='StudentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('major_credits', models.IntegerField()),
                ('ptc_major', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eligible', models.BooleanField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentrecord')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
