# Generated by Django 5.1.5 on 2025-04-14 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=8)),
                ('course_number', models.CharField(max_length=8)),
                ('course_name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_code', models.CharField(max_length=20)),
                ('catalog_year', models.IntegerField()),
                ('major_name_web', models.CharField(max_length=255)),
                ('major_name_registrar', models.CharField(max_length=255)),
                ('total_credits_required', models.IntegerField()),
            ],
            options={
                'unique_together': {('major_code', 'catalog_year')},
            },
        ),
        migrations.CreateModel(
            name='RequirementNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('credits', 'Credit Requirement'), ('choose', 'Choose One Subgroup'), ('header', 'Informational Header'), ('group', 'General Group')], max_length=20)),
                ('required_credits', models.IntegerField(blank=True, null=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.majormapping')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='src.requirementnode')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NodeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.course')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='src.requirementnode')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('high_school_grad', models.IntegerField()),
                ('first_term', models.IntegerField()),
                ('term', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('credits', models.IntegerField()),
                ('course_attributes', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(max_length=255)),
                ('student_attributes', models.BigIntegerField(blank=True, null=True)),
                ('counts_toward_major', models.BooleanField(default=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.majormapping')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('total_term_credits', models.IntegerField()),
                ('da_credits', models.IntegerField()),
                ('total_academic_year_credits', models.IntegerField()),
                ('ptc_major', models.DecimalField(decimal_places=2, max_digits=5)),
                ('satisfactory_ptc_major', models.BooleanField()),
                ('eligible', models.BooleanField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('satisfactory_gpa', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='studentrecord',
            index=models.Index(fields=['student_id'], name='src_student_student_7ad857_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrecord',
            index=models.Index(fields=['term'], name='src_student_term_f5a6d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmajor',
            unique_together={('student', 'major')},
        ),
        migrations.AlterUniqueTogether(
            name='studentaudit',
            unique_together={('student', 'term')},
        ),
    ]
