# Generated by Django 5.1.5 on 2025-03-03 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=8)),
                ('course_number', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorMapping',
            fields=[
                ('major_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='catalog_year',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='course_attribute',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='major',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='minors',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='student_attribute',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='counts_toward_major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='course_attributes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='student_attributes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='grade',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MajorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('Core', 'Core Requirement'), ('Elective', 'Elective'), ('Not Applicable', 'Not Applicable')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.majormapping')),
            ],
            options={
                'unique_together': {('major', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('major_credits', models.IntegerField()),
                ('ptc_major', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eligible', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentrecord')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_year', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.majormapping')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentrecord')),
            ],
            options={
                'unique_together': {('student', 'major')},
            },
        ),
    ]
