# Generated by Django 5.1.5 on 2025-04-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='majormapping',
            name='total_credits_required',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentaudit',
            name='satisfactory_gpa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentaudit',
            name='satisfactory_ptc_major',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
