# Generated by Django 5.1.5 on 2025-04-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='majormapping',
            name='base_major_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
