# Generated by Django 5.1.5 on 2025-04-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='declared_major_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
