# Generated by Django 5.1.5 on 2025-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_majormapping_base_major_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='ft_term_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
