# Generated by Django 5.1.5 on 2025-03-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_course_majormapping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majormapping',
            old_name='major_name',
            new_name='major_name_registrar',
        ),
        migrations.AddField(
            model_name='majormapping',
            name='major_name_web',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
