# Generated by Django 5.1.5 on 2025-04-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_majormapping_total_credits_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentaudit',
            old_name='major_credits',
            new_name='da_credits',
        ),
        migrations.RenameField(
            model_name='studentaudit',
            old_name='total_credits',
            new_name='total_term_credits',
        ),
        migrations.AddField(
            model_name='studentaudit',
            name='total_academic_year_credits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
