# Generated by Django 5.1.5 on 2025-03-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_rename_major_name_majormapping_major_name_registrar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
    ]
