# Generated by Django 5.1.5 on 2025-03-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=8),
        ),
    ]
